package org.restbucks.wechat.bff.wechat

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings
import me.chanjar.weixin.mp.api.WxMpKefuService
import me.chanjar.weixin.mp.bean.kefu.WxMpKefuMessage
import org.restbucks.wechat.bff.wechat.messaging.QrCodeScannedEventHandler
import spock.lang.Specification

@SuppressFBWarnings(value = "SnVI",
        justification = "Caused by inner classes generated by spock")
class QrCodeScannedEventHandlerSpecs extends Specification {

    def subject

    def messageSender = Mock(WxMpKefuService)

    def publicBaseUri = "https://wechat.restbucks.org"

    def setup() {
        subject = new QrCodeScannedEventHandler(messageSender)
    }

    def "it should dispatch message to corresponding handler"() {

        given: "a qrcode scanned event"

        when: "message dispatcher receives the event"
        subject.handle("qrscene_store_123", "FromUser")

        then: "should send a news message"

        with(messageSender) {
            1 * sendKefuMessage({
                it.toUser = "FromUser"
                it.msgType == "NEWS"
                it.articles.get(0).title == "Welcome to Restbucks Store 123"
                it.articles.get(0).url == publicBaseUri + "/index.html#/place-order-form/123"
            } as WxMpKefuMessage)
        }

    }
}
